# Generated by Django 4.2.7 on 2023-11-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('rooms', models.IntegerField()),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_date', models.DateTimeField(auto_now_add=True)),
                ('dael_amount', models.IntegerField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsem_dom.agent')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsem_dom.client')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsem_dom.property')),
            ],
        ),
    ]
