# Generated by Django 4.2.7 on 2023-11-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsem_dom', '0002_alter_deal_deal_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='dael_amount',
            new_name='deal_amount',
        ),
    ]
