# Generated by Django 4.2.7 on 2023-11-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsem_dom', '0003_rename_dael_amount_deal_deal_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.CharField(default='Завершен', max_length=32),
        ),
    ]
